Disable teju under miri
    error: Undefined Behavior: memory access failed: attempting to access 20 bytes, but got alloc107928+0x13 which is only 1 byte from the end of the allocation
       --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/teju/fmt.rs:178:9
        |
    178 |         core::ptr::copy_nonoverlapping(digits_ptr.add(offset), buf, 20);
        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
        |
        = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
        = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    help: alloc107928 was allocated here:
       --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/teju/fmt.rs:141:13
        |
    141 |         let mut digits = [MaybeUninit::<u8>::uninit(); 20];
        |             ^^^^^^^^^^
        = note: BACKTRACE (of the first span):
        = note: inside `teju::teju::fmt::print_u64_mantissa_known_len` at $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/teju/fmt.rs:178:9: 178:72
        = note: inside `teju::teju::f64::Result::format_general` at $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/teju/mk_impl.rs:427:17: 427:96
        = note: inside `teju::teju::f64::<impl teju::teju::float::Sealed for f64>::format_general_finite_nonzero` at $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/teju/mk_impl.rs:518:18: 518:55
        = note: inside `teju::Buffer::<f64, teju::teju::format::General>::format_finite` at $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/teju-0.1.1/src/lib.rs:122:26: 122:64
    note: inside closure
       --> src/main.rs:72:27
        |
     72 |         f64: |value, f| f(teju::Buffer::new().format_finite(value)),
        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        = note: inside `<{closure@src/main.rs:72:14: 72:24} as std::ops::FnOnce<(f64, &mut dyn for<'a> std::ops::FnMut(&'a str))>>::call_once - shim` at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5: 250:71
    note: inside `verify_value`
       --> src/main.rs:89:5
        |
     89 | /     f(value, &mut |actual| {
     90 | |         let Ok(roundtrip) = actual.parse::<f64>() else {
     91 | |             eprintln!("Error: failed to parse {actual}");
     92 | |             return;
    ...   |
     99 | |         len = actual.len();
    100 | |     });
        | |______^
    note: inside `verify`
       --> src/main.rs:111:5
        |
    111 |     verify_value(0.1, f);
        |     ^^^^^^^^^^^^^^^^^^^^
    note: inside `verify_all`
       --> src/main.rs:146:13
        |
    146 |             verify(imp.f64, imp.name);
        |             ^^^^^^^^^^^^^^^^^^^^^^^^^
    note: inside `main`
       --> src/main.rs:219:5
        |
    219 |     verify_all();
        |     ^^^^^^^^^^^^